/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    news: News;
    media: Media;
    'rental-inquiries': RentalInquiry;
    messages: Message;
    subscribers: Subscriber;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'rental-inquiries': RentalInquiriesSelect<false> | RentalInquiriesSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    rentals: Rental;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    rentals: RentalsSelect<false> | RentalsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every page on the site except Home (edit that under Home page). On Rent the Hall, Calendar, Donate, News, and Contact, your text appears at the top and the rates, calendar, donation button, news list, or form is added below it automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * The web address for this item. Leave blank to build it from the title.
   */
  slug: string;
  /**
   * Shown in larger type under the title, and used by search engines.
   */
  summary?: string | null;
  image?: (number | null) | Media;
  /**
   * Optional on pages that already have a form, calendar, or list below.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the photo for visitors who use screen readers, e.g. "The hall seen from the common in spring". For PDFs, use the document title.
   */
  alt: string;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * The web address for this item. Leave blank to build it from the title.
   */
  slug: string;
  publishedDate: string;
  /**
   * A short summary shown on the News page and the home page.
   */
  excerpt?: string | null;
  image?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Requests sent from the Rent the Hall page. Set the status as you work through each one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rental-inquiries".
 */
export interface RentalInquiry {
  id: number;
  status: 'new' | 'in-progress' | 'booked' | 'closed';
  /**
   * Only board members see these notes.
   */
  boardNotes?: string | null;
  name: string;
  organization?: string | null;
  email: string;
  phone?: string | null;
  eventType: 'private-party' | 'wedding' | 'performance' | 'dance' | 'class' | 'meeting' | 'recurring' | 'other';
  isPublic?: boolean | null;
  preferredDate: string;
  alternateDate?: string | null;
  startTime?: string | null;
  endTime?: string | null;
  attendance?: number | null;
  spaces?: ('main-hall' | 'cloakroom' | 'kitchen')[] | null;
  needsPA?: boolean | null;
  alcohol?: boolean | null;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Notes sent from the Contact page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  status: 'new' | 'answered';
  name: string;
  email: string;
  phone?: string | null;
  message: string;
  wantsNewsletter?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who asked for news by email. Copy new signups into Givebutter Contacts, then tick "Added to Givebutter".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  name?: string | null;
  source?: ('footer' | 'contact' | 'import') | null;
  addedToGivebutter?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'editor' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'rental-inquiries';
        value: number | RentalInquiry;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  image?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedDate?: T;
  excerpt?: T;
  image?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rental-inquiries_select".
 */
export interface RentalInquiriesSelect<T extends boolean = true> {
  status?: T;
  boardNotes?: T;
  name?: T;
  organization?: T;
  email?: T;
  phone?: T;
  eventType?: T;
  isPublic?: T;
  preferredDate?: T;
  alternateDate?: T;
  startTime?: T;
  endTime?: T;
  attendance?: T;
  spaces?: T;
  needsPA?: T;
  alcohol?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  wantsNewsletter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  source?: T;
  addedToGivebutter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  heroHeading: string;
  heroText: string;
  heroImage?: (number | null) | Media;
  spaces?:
    | {
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  campaignOn?: boolean | null;
  campaignHeading?: string | null;
  campaignText?: string | null;
  campaignGoal?: number | null;
  /**
   * Update from the Givebutter dashboard.
   */
  campaignRaised?: number | null;
  campaignProjects?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  campaignRecognition?: string | null;
  campaignImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The rates, other charges, FAQ, and documents on the Rent the Hall page. Only admins can change these. The page title, introduction, and photo are under Pages → Rent the Hall.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rentals".
 */
export interface Rental {
  id: number;
  intro: string;
  image?: (number | null) | Media;
  seasons?:
    | {
        name: string;
        dates: string;
        hourly: number;
        hourlyLimit?: number | null;
        dayRate: number;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  extras?:
    | {
        item: string;
        price: string;
        id?: string | null;
      }[]
    | null;
  rateNotes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  documents?:
    | {
        label: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  streetAddress: string;
  mailingAddress: string;
  email: string;
  notificationEmail: string;
  facebookUrl?: string | null;
  mapUrl?: string | null;
  /**
   * From Google Calendar → Settings → this calendar → "Integrate calendar" → Calendar ID. The calendar must be set to public.
   */
  googleCalendarId?: string | null;
  /**
   * Where the Donate button goes, e.g. the Givebutter campaign link once it is published, or a PayPal donate link. Leave blank to show only the mail-a-check instructions.
   */
  donateUrl?: string | null;
  /**
   * Optional. Fill in both Givebutter fields to show the donation form on the page itself instead of the button.
   */
  givebutterAccountId?: string | null;
  /**
   * The code at the end of the campaign link, e.g. the "mch2026" in givebutter.com/mch2026.
   */
  givebutterCampaignCode?: string | null;
  announcementOn?: boolean | null;
  announcementText?: string | null;
  announcementLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroHeading?: T;
  heroText?: T;
  heroImage?: T;
  spaces?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  campaignOn?: T;
  campaignHeading?: T;
  campaignText?: T;
  campaignGoal?: T;
  campaignRaised?: T;
  campaignProjects?:
    | T
    | {
        item?: T;
        id?: T;
      };
  campaignRecognition?: T;
  campaignImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rentals_select".
 */
export interface RentalsSelect<T extends boolean = true> {
  intro?: T;
  image?: T;
  seasons?:
    | T
    | {
        name?: T;
        dates?: T;
        hourly?: T;
        hourlyLimit?: T;
        dayRate?: T;
        note?: T;
        id?: T;
      };
  extras?:
    | T
    | {
        item?: T;
        price?: T;
        id?: T;
      };
  rateNotes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  streetAddress?: T;
  mailingAddress?: T;
  email?: T;
  notificationEmail?: T;
  facebookUrl?: T;
  mapUrl?: T;
  googleCalendarId?: T;
  donateUrl?: T;
  givebutterAccountId?: T;
  givebutterCampaignCode?: T;
  announcementOn?: T;
  announcementText?: T;
  announcementLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}